"""Add race scheduling models

Revision ID: 8a5befbe0704
Revises: a148e5db0aab
Create Date: 2025-04-14 07:52:11.360197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5befbe0704'
down_revision = 'a148e5db0aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lane_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('race_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lane_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lane_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_race_result_lane_id', 'lane', ['lane_id'], ['id'])
        batch_op.drop_column('lane')

    with op.batch_alter_table('racer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racer', schema=None) as batch_op:
        batch_op.drop_column('check_in_time')
        batch_op.drop_column('checked_in')

    with op.batch_alter_table('race_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lane', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_race_result_lane_id', type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('lane_number')
        batch_op.drop_column('lane_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('lane_count')

    # ### end Alembic commands ###
